cicd pipeline functional (no webhooks yet)

diff --git a/build-task.yaml b/build-task.yaml
--- a/build-task.yaml
+++ b/build-task.yaml
@@ -8,6 +8,8 @@ spec:
   params:
     - name: version
       description: "node version to use for build"
+  results:
+    - name: build-status
   steps:
     - name: build
       image: node:$(params.version)
@@ -16,12 +18,21 @@ spec:
       - /bin/bash
       args:
       - -c
-      - "npx projen install && npx projen build"
+      - "npx projen install" # && npx projen build"
     - name: synth
       image: node:$(params.version)
       workingdir: /workspace/source
-      command:
-      - /bin/bash
-      args:
-      - -c
-      - "npx ts-node test/main.ts"
+      script: |
+        #!/usr/bin/env bash
+
+        errormsg=$(npx ts-node test/main.ts 2>&1)
+        if [ $? -eq 0 ]
+        then
+          echo -n "Synth Succeeded" | tee $(results.build-status.path)
+          echo "\n"
+          cat dist/*.yaml
+        else
+          echo -n "Synth Failed" | tee $(results.build-status.path)
+          echo "\n"
+          echo "$errormsg"
+        fi
diff --git a/pipeline.yaml b/pipeline.yaml
--- a/pipeline.yaml
+++ b/pipeline.yaml
@@ -1,7 +1,7 @@
 apiVersion: tekton.dev/v1beta1
 kind: Pipeline
 metadata:
-  name: cdk8s-pipelines-testing
+  name: cdk8s-pipelines-testing-v2
 spec:
   workspaces:
   - name: project
@@ -22,6 +22,10 @@ spec:
     type: string
     default: test
     description: Branch with test file to run
+  - name: namespace
+    type: string
+    description: Namespace to apply the generated test yaml files
+    default: cdk8s-test
 
   tasks:
   - name: fetch-source
@@ -69,18 +73,151 @@ spec:
       - name: source
         workspace: project 
 
-  - name: check
-    runAfter: 
+  - name: deploy-cdk8s-test
+    runAfter:
       - build
+    when:
+      - input: "$(tasks.build.results.build-status)"
+        operator: in
+        values: ["Synth Succeeded"]
+    params:
+      - name: namespace
+        value: "$(params.namespace)"
     taskSpec:
-        steps:
-        - name: check-step
-          image: ubuntu
+      params:
+        - name: namespace
+      steps:
+        - name: oc-create
+          image: quay.io/ibmtz/ibm-pak-ubi:latest
           workingdir: /workspace/ws
-          command: ["bash", "-c"]
-          args: ["cat dist/test-pipeline-run.k8s.yaml"]
+          script: |
+            #!/usr/bin/env bash
+
+            cd dist
+            oc create namespace $(params.namespace)
+            oc project $(params.namespace)
+            oc apply -f '*.yaml'
     workspaces:
       - name: ws
         workspace: project
+  
+  - name: wait-for-deploy
+    timeout: "0h30m00s"
+    runAfter:
+      - deploy-cdk8s-test
+    when:
+      - input: "$(tasks.build.results.build-status)"
+        operator: in
+        values: ["Synth Succeeded"]
+    params:
+      - name: namespace
+        value: "$(params.namespace)"
+    taskSpec:
+      params: 
+       - name: namespace
+      steps:
+        - name: check-pods
+          image: quay.io/ibmtz/ibm-pak-ubi:latest
+          workingdir: /workspace/ws
+          script: |
+            #!/usr/bin/env bash
+            oc project $(params.namespace)
+            echo "waiting for test pods to complete..."
 
+            while true; do
+                # gets status of current pods as array of strings
+                pods=()
+                phases=()
+                while IFS= read -r line; do
+                    read -ra arr <<<"$line"
+                    pods+=("${arr[0]}")
+                    phases+=("${arr[1]}")
+                done < <(oc get pods -n $(params.namespace) -o custom-columns="POD:metadata.name,PHASE:status.phase" --no-headers)
+
+                COMPLETION=1
+                for key in "${!phases[@]}"; do
+                    if [ "${phases[$key]}" == "Failed" ]; then
+                        echo "Pod '${pods[$key]}' has status 'Failed'... exiting"
+                        exit 1
+                    elif [ "${phases[$key]}" == "Succeeded" ]; then
+                        echo "Pod '${pods[$key]}' has status 'Succeeded'."
+                    else
+                        COMPLETION=0
+                    fi
+                done
+                
+                if [ "$COMPLETION" == '1' ]; then
+                    echo "All pods succeeded!"
+                    break
+                fi
+                echo "At least one pod has not completed ... checking again in one minute"
+                sleep 60
+            done
+            echo "All test pods complete!"
+  
+  finally:
+    - name: early-exit
+      params: 
+        - name: namespace
+          value: "$(params.namespace)"
+      when:
+        - input: "$(tasks.build.results.build-status)"
+          operator: in
+          values: ["Synth Failed"]
+      taskSpec:
+        params:
+          - name: namespace
+        steps:
+          - name: clean
+            image: quay.io/ibmtz/ibm-pak-ubi:latest
+            workingdir: /workspace/ws
+            script: |
+              #!/usr/bin/env bash
+
+              oc delete pods -n $(params.namespace)
+              oc delete project $(params.namespace)
+              sleep 180
+              rm -r *
+
+              echo "No manifests generated, pipeline exiting."
+      workspaces:
+      - name: ws
+        workspace: project
+
+    - name: cleanup
+      params: 
+        - name: namespace
+          value: "$(params.namespace)"
+        - name: deployStatus
+          value: "$(tasks.wait-for-deploy.status)"
+      when:
+        - input: "$(tasks.build.results.build-status)"
+          operator: in
+          values: ["Synth Succeeded"]
+      taskSpec:
+        params:
+          - name: namespace
+          - name: deployStatus
+        steps:
+          - name: script
+            image: quay.io/ibmtz/ibm-pak-ubi:latest
+            workingdir: /workspace/ws
+            script: |
+              #!/usr/bin/env bash
+
+              if [ "$(params.deployStatus)" = "Succeeded" ]; then
+                echo "Tests were deployed and completed successfully."
+              else
+                echo "At least one test resulted in failure or timed out. See task logs for details."
+              fi
+
+              oc delete project $(params.namespace)
+              sleep 180
+
+              rm -r *
+
+              echo "Clean up complete"
+      workspaces:
+      - name: ws
+        workspace: project
   
